### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by ibr5500** [ibr5500/Portfolio#8]
this is code review for morning session

**Comment by ibr5500** [comment]
Please, add width 375px for the navbar. Because it is bigger than the Figma design.

**Comment by S-imba** [comment]
Hello @ibr5500 
Your code is clean and I enjoyed going through it
![image](https://user-images.githubusercontent.com/57634593/159864612-39eb96ec-0bbd-494c-be9d-7ecfb694f860.png)

**Comment by Kwentsir** [comment]
You have done a great job by writing this code. Your code looks so clean. Please, I kindly suggest you add a pattern to the email input so that it rejects wrong emails.

**Comment by nmeziany** [comment]
You made a great Job 💯 but I have some remarks:
          I suggest you to use a pattern for the email box to force the user to enter a valid email.
